"""empty message

Revision ID: 729274a93f85
Revises: None
Create Date: 2016-08-02 19:50:03.323705

"""

# revision identifiers, used by Alembic.
revision = '729274a93f85'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('firstname', sa.String(length=120), nullable=True),
    sa.Column('lastname', sa.String(length=120), nullable=True),
    sa.Column('gender', sa.String(length=30), nullable=True),
    sa.Column('picture', sa.String(length=120), nullable=True),
    sa.Column('access_token', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id', 'email'),
    sa.UniqueConstraint('access_token'),
    sa.UniqueConstraint('email')
    )
    op.drop_table('test')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.drop_table('user')
    ### end Alembic commands ###
